[package]
name = "music_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-music-theory = "0.2.0"
ghakuf = "0.5.6"
